const questionsByMode = {
    easy: [
        { jp: "私はコーヒーが好きです。", en: "I like coffee." },
        { jp: "彼は毎日そこへ行きます。", en: "He goes there every day." },
        { jp: "これを持ってください。", en: "Please have this." },
        { jp: "少し休みましょう。", en: "Let's take a break." },
        { jp: "あなたはそれをどう思いますか？", en: "What do you think about it?" },
        { jp: "彼らは夕食を作っています。", en: "They are making dinner." },
        { jp: "私は新しいペンを買いました。", en: "I got a new pen." },
        { jp: "明日は早く起きます。", en: "I will get up early tomorrow." },
        { jp: "これを見てください。", en: "Look at this." },
        { jp: "彼は先生です。", en: "He is a teacher." },
        { jp: "私は車を持っていません。", en: "I don't have a car." },
        { jp: "ここで待っていてください。", en: "Please wait here." },
        { jp: "彼女はとても上手に英語を話します。", en: "She speaks English very well." },
        { jp: "私は昨日、本を読みました。", en: "I read a book yesterday." },
        { jp: "私たちは来週会います。", en: "We will meet next week." },
        { jp: "あなたのペンを使ってもいいですか？", en: "Can I use your pen?" },
        { jp: "彼は私の友達です。", en: "He is my friend." },
        { jp: "それを教えてください。", en: "Please tell me that." },
        { jp: "私は歩いて学校へ行きます。", en: "I go to school on foot." },
        { jp: "彼女は彼を知りません。", en: "She doesn't know him." },
        { jp: "私はそれを必要としています。", en: "I need it." },
        { jp: "もう一度言ってください。", en: "Please say that again." },
        { jp: "私はそれをしたいと思います。", en: "I want to do that." },
        { jp: "今何時ですか？", en: "What time is it?" },
        { jp: "私はその答えを知っています。", en: "I know the answer." },
        { jp: "彼はどこに住んでいますか？", en: "Where does he live?" },
        { jp: "私は彼に電話します。", en: "I will call him." },
        { jp: "彼女は音楽を聴くのが好きです。", en: "She likes to listen to music." },
        { jp: "私は毎朝走ります。", en: "I run every morning." },
        { jp: "それを私にください。", en: "Give it to me." }
    ],
    normal: [
        { jp: "会議は3時に始まります。", en: "The meeting will start at 3 o'clock." },
        { jp: "彼にメールを送っておきます。", en: "I will send him an email." },
        { jp: "彼はその計画を説明しました。", en: "He explained the plan." },
        { jp: "私はそのプロジェクトを担当しています。", en: "I am in charge of the project." },
        { jp: "金曜日までにそれを終わらせる必要があります。", en: "I need to finish it by Friday." },
        { jp: "タクシーに乗りましょう。", en: "Let's take a taxi." },
        { jp: "彼は約束を破ったことがない。", en: "He has never broken his promise." },
        { jp: "彼女に伝言をお願いできますか？", en: "Could you leave a message for her?" },
        { jp: "私たちはその問題について話し合いました。", en: "We discussed the problem." },
        { jp: "来週、出張で東京に行きます。", en: "I am going to Tokyo on a business trip next week." },
        { jp: "新しいパソコンを設定しなければなりません。", en: "I have to set up my new computer." },
        { jp: "彼はいつも早く仕事に来ます。", en: "He always comes to work early." },
        { jp: "その文書を印刷していただけますか？", en: "Could you print out the document?" },
        { jp: "私は彼の意見に賛成です。", en: "I agree with his opinion." },
        { jp: "この製品はとても人気があります。", en: "This product is very popular." },
        { jp: "私たちは新しいシステムを導入しました。", en: "We introduced a new system." },
        { jp: "彼はその会社を辞めました。", en: "He quit the company." },
        { jp: "お時間をいただいてありがとうございます。", en: "Thank you for taking your time." },
        { jp: "私はこの分野で5年の経験があります。", en: "I have five years of experience in this field." },
        { jp: "来月、新しい店舗をオープンします。", en: "We will open a new store next month." },
        { jp: "彼は重要な役割を果たしています。", en: "He plays an important role." },
        { jp: "その提案を受け入れることはできません。", en: "We cannot accept the proposal." },
        { jp: "私はクライアントと会う予定です。", en: "I am planning to meet with a client." },
        { jp: "このソフトウェアは使いやすいです。", en: "This software is easy to use." },
        { jp: "チームメンバーにお知らせします。", en: "I will let the team members know." },
        { jp: "私たちはその問題を解決する方法を見つけました。", en: "We found a way to solve the problem." },
        { jp: "予算について話し合う必要があります。", en: "We need to talk about the budget." },
        { jp: "彼女はとても優秀なエンジニアです。", en: "She is a very excellent engineer." },
        { jp: "その計画は順調に進んでいます。", en: "The plan is going well." },
        { jp: "ご質問はありますか？", en: "Do you have any questions?" }
    ],
    hard: [
        { jp: "彼はその状況を利用して自分の利益にしました。", en: "He took advantage of the situation for his own benefit." },
        { jp: "彼女は不可能な要求を押し付けてきました。", en: "She imposed an impossible demand on us." },
        { jp: "このプロジェクトを軌道に乗せる必要があります。", en: "We need to get this project off the ground." },
        { jp: "彼はその新しい方針に異議を唱えました。", en: "He objected to the new policy." },
        { jp: "私たちは最終期限を守るために努力しています。", en: "We are striving to meet the deadline." },
        { jp: "その問題に対処する明確な戦略が必要です。", en: "We need a clear strategy to deal with the problem." },
        { jp: "彼女は困難な状況を打破する能力があります。", en: "She has the ability to overcome difficult situations." },
        { jp: "我々は競合他社に先んじるための対策を講じています。", en: "We are taking measures to stay ahead of our competitors." },
        { jp: "この契約にはいくつかの複雑な条項が含まれています。", en: "This contract contains several complex clauses." },
        { jp: "彼らは市場の動向を綿密に分析しています。", en: "They are analyzing the market trends closely." },
        { jp: "その決定は会社全体に影響を及ぼすでしょう。", en: "The decision will affect the whole company." },
        { jp: "私たちはリスクを最小限に抑えなければなりません。", en: "We must minimize the risks." },
        { jp: "彼はその提案の実現可能性を評価しています。", en: "He is evaluating the feasibility of the proposal." },
        { jp: "その新製品の発売は延期されました。", en: "The launch of the new product was postponed." },
        { jp: "私たちはお客様からのフィードバックを反映させています。", en: "We are incorporating feedback from our customers." },
        { jp: "彼は常に冷静さを保ち、適切な判断を下します。", en: "He always keeps calm and makes appropriate decisions." },
        { jp: "その会社は経営破綻の危機に瀕しています。", en: "The company is on the verge of bankruptcy." },
        { jp: "私たちは生産性を向上させる新しい方法を探しています。", en: "We are looking for new ways to improve productivity." },
        { jp: "彼女はチームの士気を高めるために尽力しています。", en: "She is making efforts to boost the team's morale." },
        { jp: "その合併は業界全体に波紋を呼びました。", en: "The merger caused a ripple effect throughout the industry." },
        { jp: "私たちは厳格な品質管理基準を設けています。", en: "We have established strict quality control standards." },
        { jp: "彼はその交渉で主導権を握りました。", en: "He took the initiative in the negotiation." },
        { jp: "その規制が緩和されれば、新たなビジネスチャンスが生まれます。", en: "If the regulations are relaxed, new business opportunities will arise." },
        { jp: "私たちは長期的な視野を持って計画を立てるべきです。", en: "We should make plans with a long-term perspective." },
        { jp: "彼女は複雑なデータをわかりやすく可視化しました。", en: "She visualized complex data in an easy-to-understand way." },
        { jp: "その投資は莫大な利益をもたらしました。", en: "The investment yielded a huge profit." },
        { jp: "私たちは顧客満足度を最優先に考えています。", en: "We prioritize customer satisfaction above all else." },
        { jp: "彼は時代の変化に柔軟に対応しています。", en: "He is responding flexibly to the changing times." },
        { jp: "そのプロジェクトの失敗から私たちは多くを学びました。", en: "We learned a lot from the failure of the project." },
        { jp: "私たちは持続可能な社会の実現に向けて貢献しています。", en: "We are contributing to the realization of a sustainable society." }
    ]
};
