const questionsByMode = {
    easy: [
        { jp: "猫がテーブルの上にいます。", en: "There is a cat on the table." },
        { jp: "明日は晴れるでしょう。", en: "It will be sunny tomorrow." },
        { jp: "彼女はとても親切です。", en: "She is very kind." },
        { jp: "その本は面白かったです。", en: "The book was interesting." },
        { jp: "窓を開けてくれませんか？", en: "Could you open the window?" },
        { jp: "彼らは夕食を作っています。", en: "They are making dinner." },
        { jp: "私は新しいペンを買いました。", en: "I got a new pen." },
        { jp: "明日は早く起きます。", en: "I will get up early tomorrow." },
        { jp: "これを見てください。", en: "Look at this." },
        { jp: "彼は先生です。", en: "He is a teacher." },
        { jp: "私は車を持っていません。", en: "I don't have a car." },
        { jp: "ここで待っていてください。", en: "Please wait here." },
        { jp: "彼女はとても上手に英語を話します。", en: "She speaks English very well." },
        { jp: "私は昨日、本を読みました。", en: "I read a book yesterday." },
        { jp: "私たちは来週会います。", en: "We will meet next week." },
        { jp: "あなたのペンを使ってもいいですか？", en: "Can I use your pen?" },
        { jp: "彼は私の友達です。", en: "He is my friend." },
        { jp: "それを教えてください。", en: "Please tell me that." },
        { jp: "私は歩いて学校へ行きます。", en: "I go to school on foot." },
        { jp: "彼女は彼を知りません。", en: "She doesn't know him." },
        { jp: "私はそれを必要としています。", en: "I need it." },
        { jp: "もう一度言ってください。", en: "Please say that again." },
        { jp: "私はそれをしたいと思います。", en: "I want to do that." },
        { jp: "今何時ですか？", en: "What time is it?" },
        { jp: "私はその答えを知っています。", en: "I know the answer." },
        { jp: "彼はどこに住んでいますか？", en: "Where does he live?" },
        { jp: "私は彼に電話します。", en: "I will call him." },
        { jp: "彼女は音楽を聴くのが好きです。", en: "She likes to listen to music." },
        { jp: "私は毎朝走ります。", en: "I run every morning." },
        { jp: "それを私にください。", en: "Give it to me." }
    ],
    normal: [
        { jp: "私は昨日、映画を見に行きました。", en: "I went to see a movie yesterday." },
        { jp: "彼が来たら教えてください。", en: "Please let me know when he comes." },
        { jp: "このパソコンは高すぎます。", en: "This computer is too expensive." },
        { jp: "京都に行ったことがありますか？", en: "Have you ever been to Kyoto?" },
        { jp: "彼女は私が何を言いたいのか理解しました。", en: "She understood what I wanted to say." },
        { jp: "タクシーに乗りましょう。", en: "Let's take a taxi." },
        { jp: "彼は約束を破ったことがない。", en: "He has never broken his promise." },
        { jp: "彼女に伝言をお願いできますか？", en: "Could you leave a message for her?" },
        { jp: "私たちはその問題について話し合いました。", en: "We discussed the problem." },
        { jp: "来週、出張で東京に行きます。", en: "I am going to Tokyo on a business trip next week." },
        { jp: "新しいパソコンを設定しなければなりません。", en: "I have to set up my new computer." },
        { jp: "彼はいつも早く仕事に来ます。", en: "He always comes to work early." },
        { jp: "その文書を印刷していただけますか？", en: "Could you print out the document?" },
        { jp: "私は彼の意見に賛成です。", en: "I agree with his opinion." },
        { jp: "この製品はとても人気があります。", en: "This product is very popular." },
        { jp: "私たちは新しいシステムを導入しました。", en: "We introduced a new system." },
        { jp: "彼はその会社を辞めました。", en: "He quit the company." },
        { jp: "お時間をいただいてありがとうございます。", en: "Thank you for taking your time." },
        { jp: "私はこの分野で5年の経験があります。", en: "I have five years of experience in this field." },
        { jp: "来月、新しい店舗をオープンします。", en: "We will open a new store next month." },
        { jp: "彼は重要な役割を果たしています。", en: "He plays an important role." },
        { jp: "その提案を受け入れることはできません。", en: "We cannot accept the proposal." },
        { jp: "私はクライアントと会う予定です。", en: "I am planning to meet with a client." },
        { jp: "このソフトウェアは使いやすいです。", en: "This software is easy to use." },
        { jp: "チームメンバーにお知らせします。", en: "I will let the team members know." },
        { jp: "私たちはその問題を解決する方法を見つけました。", en: "We found a way to solve the problem." },
        { jp: "予算について話し合う必要があります。", en: "We need to talk about the budget." },
        { jp: "彼女はとても優秀なエンジニアです。", en: "She is a very excellent engineer." },
        { jp: "その計画は順調に進んでいます。", en: "The plan is going well." },
        { jp: "ご質問はありますか？", en: "Do you have any questions?" }
    ],
    hard: [
        { jp: "その新しい法律は来月から施行されます。", en: "The new law will take effect from next month." },
        { jp: "彼は自らの過ちを率直に認め、謝罪した。", en: "He frankly admitted his mistake and apologized." },
        { jp: "我が社は環境保護に配慮した製品開発を心がけています。", en: "Our company is committed to developing products that are environmentally friendly." },
        { jp: "その画期的な技術は私たちの生活を根本から変えるだろう。", en: "The breakthrough technology will fundamentally change our lives." },
        { jp: "彼は豊富な経験と深い知識に裏打ちされた説得力のあるプレゼンを行った。", en: "He delivered a persuasive presentation backed by extensive experience and deep knowledge." },
        { jp: "その問題に対処する明確な戦略が必要です。", en: "We need a clear strategy to deal with the problem." },
        { jp: "彼女は困難な状況を打破する能力があります。", en: "She has the ability to overcome difficult situations." },
        { jp: "我々は競合他社に先んじるための対策を講じています。", en: "We are taking measures to stay ahead of our competitors." },
        { jp: "この契約にはいくつかの複雑な条項が含まれています。", en: "This contract contains several complex clauses." },
        { jp: "彼らは市場の動向を綿密に分析しています。", en: "They are analyzing the market trends closely." },
        { jp: "その決定は会社全体に影響を及ぼすでしょう。", en: "The decision will affect the whole company." },
        { jp: "私たちはリスクを最小限に抑えなければなりません。", en: "We must minimize the risks." },
        { jp: "彼はその提案の実現可能性を評価しています。", en: "He is evaluating the feasibility of the proposal." },
        { jp: "その新製品の発売は延期されました。", en: "The launch of the new product was postponed." },
        { jp: "私たちはお客様からのフィードバックを反映させています。", en: "We are incorporating feedback from our customers." },
        { jp: "彼は常に冷静さを保ち、適切な判断を下します。", en: "He always keeps calm and makes appropriate decisions." },
        { jp: "その会社は経営破綻の危機に瀕しています。", en: "The company is on the verge of bankruptcy." },
        { jp: "私たちは生産性を向上させる新しい方法を探しています。", en: "We are looking for new ways to improve productivity." },
        { jp: "彼女はチームの士気を高めるために尽力しています。", en: "She is making efforts to boost the team's morale." },
        { jp: "その合併は業界全体に波紋を呼びました。", en: "The merger caused a ripple effect throughout the industry." },
        { jp: "私たちは厳格な品質管理基準を設けています。", en: "We have established strict quality control standards." },
        { jp: "彼はその交渉で主導権を握りました。", en: "He took the initiative in the negotiation." },
        { jp: "その規制が緩和されれば、新たなビジネスチャンスが生まれます。", en: "If the regulations are relaxed, new business opportunities will arise." },
        { jp: "私たちは長期的な視野を持って計画を立てるべきです。", en: "We should make plans with a long-term perspective." },
        { jp: "彼女は複雑なデータをわかりやすく可視化しました。", en: "She visualized complex data in an easy-to-understand way." },
        { jp: "その投資は莫大な利益をもたらしました。", en: "The investment yielded a huge profit." },
        { jp: "私たちは顧客満足度を最優先に考えています。", en: "We prioritize customer satisfaction above all else." },
        { jp: "彼は時代の変化に柔軟に対応しています。", en: "He is responding flexibly to the changing times." },
        { jp: "そのプロジェクトの失敗から私たちは多くを学びました。", en: "We learned a lot from the failure of the project." },
        { jp: "私たちは持続可能な社会の実現に向けて貢献しています。", en: "We are contributing to the realization of a sustainable society." }
    ],
    "Best 125 Verbs": [
        { jp: "そこへは行かないようにと地元の人が忠告してくれたよ。", en: "The locals advised me not to go there." },
        { jp: "彼がその仕事に最も適した人だと、皆で意見が一致したよ。", en: "We all agreed he is the best person for the job." },
        { jp: "発表者は私の質問に答えてくれなかった。", en: "The speaker didn't answer my question." },
        { jp: "8時にホテルに迎えに行くように車を手配しますね。", en: "I'll arrange for a car to pick you up at your hotel, at 8." },
        { jp: "私、同僚3名と上司が打ち合わせに出席しました。", en: "Our boss, 3 co-workers & I attended the meeting." },
        { jp: "彼らは1週間トレーニングを共にした後、仲間となりました。", en: "They became friends after training all week together." },
        { jp: "白い紙（何も書かれていない紙）をいくつか持ってきてくれる？", en: "Can you please bring me some blank paper?" },
        { jp: "彼がその重い箱を運んでくれました。", en: "He carried the heavy box for me." },
        { jp: "ドアが施錠されていることを確認しましたか。", en: "Did you check the door was locked?" },
        { jp: "除菌剤でそのテーブルをきれいにしてください。", en: "Please clean the tables with disinfectant." },
        { jp: "パーティーのお金を集めさせていただきます。", en: "I'd like to collect the money for the party." },
        { jp: "義理の両親が週末に会いに来ます。", en: "My parents-in-law will come to see us, on the weekend." },
        { jp: "彼はそのサービスに絶対文句を言わない。", en: "He never complains about the service." },
        { jp: "リストのあなたの氏名に間違いがないか確認下さい。", en: "Please confirm your name on the list." },
        { jp: "その報告書については鈴木さんに連絡する必要があります。", en: "You need to contact Mr. Suzuki about the report." },
        { jp: "この書類は機密情報を含みます。", en: "This document contains confidential information." },
        { jp: "この中古車は３千ドルします。", en: "This second-hand car costs $3,000." },
        { jp: "その新しい規則で私の仕事量が減りました。", en: "My workload has decreased with the new regulations." },
        { jp: "悪天候で私の飛行機が遅れました。", en: "My flight was delayed due to bad weather." },
        { jp: "ビジネスを行う新しい方法を開発する必要があります。", en: "We need to develop new ways of doing business." },
        { jp: "彼は私の言う事全てに反対する。", en: "He disagrees with everything I say." },
        { jp: "彼は集中する必要があるので、邪魔しないように。", en: "Don't disturb him, he needs to concentrate." },
        { jp: "私達は金曜日までにその宿題をやらなくちゃ。", en: "We have to do the homework by Friday." },
        { jp: "彼はつまずいて小銭入れを落とした。", en: "He tripped and dropped his coin purse." },
        { jp: "あなたのパスポートはあと１か月で失効します。", en: "Your passport will expire in 1 month." },
        { jp: "もう一度説明してくれますか。", en: "Can you please explain that again?" },
        { jp: "彼は試験に落ちたが、2回目で受かった。", en: "He failed his test, but he passed it the 2nd time." },
        { jp: "彼女は私のグラスにビールをなみなみといだ。", en: "She filled my glass with beer." },
        { jp: "ディラン、あなたの場所（家）を見つけるのは簡単ですか。", en: "Dillian, is it easy to find your place?" },
        { jp: "いつ仕事が終わりますか。", en: "When will you finish your work?" },
        { jp: "扇風機が壊れています。あなた修理できる？", en: "The fan is broken. Can you fix it?" },
        { jp: "私についてきて。ここからはそんなに遠くないよ。", en: "Please follow me. It's not far from here." },
        { jp: "その博物館はフラッシュ撮影を禁止しています。", en: "The museum forbids flash photography." },
        { jp: "敵を許すということは、そう簡単な事ではない。", en: "It's never easy to forgive your enemies." },
        { jp: "間近で見る事で多くの経験を得ることができます。", en: "You can gain a lot of experience from watching closely." },
        { jp: "おにぎりを2つ買いに行ってくれる。", en: "Can you please go get me a couple of rice balls?" },
        { jp: "若い女性はその状況をとてもよく処理した。", en: "The young lady handled the situation very well." },
        { jp: "急に小銭持ってる？", en: "Do you have any spare change on you?" },
        { jp: "彼女の声はとても小さく、言っている事が聞こえなかった。", en: "Her voice was so soft I couldn't hear what she said." },
        { jp: "箱を開けるのを手伝いましょうか。", en: "Shall I help you (unpack) the boxes?" },
        { jp: "気兼ねなく私に質問して下さい。", en: "Please don't hesitate to ask (me) questions." },
        { jp: "毎週打ち合わせを開催するべきです。", en: "We should hold a meeting weekly / every week." },
        { jp: "急いで！電車が出発するよ。", en: "Please hurry! The train is about to leave." },
        { jp: "毎日笑う事は、あなたの健康状態を改善する。", en: "Laughing everyday improves your health." },
        { jp: "その価格は、飛行機代と3泊分の宿泊を含みます。", en: "The price includes flights & 3 nights' accommodation." },
        { jp: "今四半期、輸出が5％増えました。", en: "Exports increased by 5%, this quarter." },
        { jp: "彼は12時半に出発しなければと私達に知らせた。", en: "He informed us that he had to leave at 12:30." },
        { jp: "おじゃまします。あなたが欲しいファイルはこれですか。", en: "Sorry to interrupt you. Is this the file you wanted?" },
        { jp: "あなたを私達のスタッフ全員に紹介させていただきます。", en: "I'd like to introduce you to all of our staff." },
        { jp: "あなたのパーティーに招待してくれてありがとう。", en: "Thank you for inviting me to your party." },
        { jp: "気に入ったなら、その雑誌を持っていてもいいよ。", en: "You can keep that magazine, if you like it." },
        { jp: "彼の失礼な発言であなたが怒ったのは、知っています。", en: "I know you got angry by his rude remark." },
        { jp: "一週間持たせるのに、1000円しか持ってない。", en: "I've only got ¥1000 to last me all week." },
        { jp: "食べ物を皿に残すのは悪いマナーです。", en: "It's bad manners to leave food on your plate." },
        { jp: "分かり次第、私に知らせて下さい。", en: "Please let me know as soon as you find out." },
        { jp: "これらの箱を持ち上げるのを手伝ってくれる。", en: "Can you please help me lift these boxes?" },
        { jp: "私の言う事を聞かなかったから私達は道に迷った。", en: "You didn't listen to me, what I said, so we got lost." },
        { jp: "経営者はいつもコスト削減の方法を探ってます。", en: "Management is always looking at ways to cut costs." },
        { jp: "だれかコーヒーを淹れてくれる。", en: "Can someone please make some coffee?" },
        { jp: "彼女は大学時代にラグビーチームを管理してました。", en: "She managed the rugby team in her university days." },
        { jp: "私達は隔週で昼食をとるために会ってます。", en: "We meet for lunch every other week." },
        { jp: "映画の最初のシーンを見逃すと、最悪の気分になる。", en: "I hate it when I miss the opening scene of the movie." },
        { jp: "昨夜、ジェシーがパーティーを途中で抜けたのを誰も気づかなかった。", en: "No one noticed that Jessi left with Jessi, last night." },
        { jp: "その店主は最終的には、もっと良い割引を差し出した。", en: "The shopkeeper finally offered us a better discount." },
        { jp: "カップ麺はネットで注文する方が安いよ。", en: "It's cheaper to order the cup noodles on the Internet." },
        { jp: "私達は外国人ゲストのためにパーティーを準備しています。", en: "We're organizing a party for our foreign guests." },
        { jp: "前回のパーティーのお金、まだ私にいくらかあるよ。", en: "You still owe me money from the last party." },
        { jp: "全てを丁寧に荷造りして。", en: "Make sure you pack everything in carefully." },
        { jp: "ここに駐車するのは違反です。それは私有地です。", en: "It's illegal to park here. It's private property." },
        { jp: "ティッシュ（の箱）をとってくれますか。", en: "Can you please pass me the (box of) tissues?" },
        { jp: "いつ定期購読のお金を払う必要がありますか。", en: "When do I need to pay (for) the subscription?" },
        { jp: "今回は最短ルートを取るようにしたよ。", en: "We tried to pick the shortest route, this time." },
        { jp: "5時に事務所を出るつもりです。", en: "I'm planning to leave the office at 5." },
        { jp: "カメラを私に向けないで下さい。", en: "Please don't point your camera at me." },
        { jp: "そのイベントは10月に延期されました。", en: "The event has been postponed until October." },
        { jp: "私達の上司がビールを皆につぎました。", en: "Our boss poured drinks for everyone." },
        { jp: "太陽から目を保護することは重要です。", en: "It's important to protect your eyes from the sun." },
        { jp: "その箱を棚の上に置いてくれますか。", en: "Can you please put the box on the shelf?" },
        { jp: "たばこをやめたらすぐ体重が増えた。", en: "As soon as I quit smoking, I put on weight." },
        { jp: "11時半に姫路城に到着します。", en: "We will reach Himeji Castle at 11:30." },
        { jp: "この近くでいい軽食屋をどこかお勧めしてくれますか。", en: "Can you recommend (us) a good snack bar, near here?" },
        { jp: "私達は使うトイレットペーパーの量を減らす必要があります。", en: "We need to reduce the amount of toilet paper we use." },
        { jp: "静かなビーチでリラックスしたい。", en: "I want to relax on a quiet beach." },
        { jp: "どのような契約もサインした覚えがありません。", en: "I don't remember signing any contract." },
        { jp: "帰りにパーティーのための軽食を買うのを忘れないように言ってね。", en: "Remind me to buy some snacks for the party, on the way home." },
        { jp: "慎重にフタを取ってからかき混ぜて下さい。", en: "Carefully remove the lid and stir." },
        { jp: "電池を入れ替えなくちゃ。", en: "I need to replace the batteries." },
        { jp: "ヘンリーは私のメールに返信しなかった。", en: "Henry didn't reply to my e-mail." },
        { jp: "私達は皆、R&Rを必要としている。", en: "We all require some R&R." },
        { jp: "仙台まで新幹線の座席を２席予約したいのですが。", en: "I'd like to reserve 2 seats on the bullet train to Sendai." },
        { jp: "地下でのテーブルと椅子を返却しましたか。", en: "Did you return the table & chairs to the basement?" },
        { jp: "彼女に地下鉄に乗らないように伝えた。", en: "I told her not to ride the subway at night." },
        { jp: "今晩８時前にクライドに電話してくれますか。", en: "Can you please ring Clyde before 8, tonight?" },
        { jp: "その物語の最後には、誰も満足しない。", en: "The story's ending won't satisfy everyone." },
        { jp: "私の席をとっておいて下さい。", en: "Will you please save a seat for me?" },
        { jp: "最近ミランダを見かけた？", en: "Have you seen Miranda lately?" },
        { jp: "私の自転車をクレアに50ポンドで売ったよ。", en: "I sold my bike to Claire, for £50." },
        { jp: "これを急便で送っていただきたいです。", en: "I'd like to send this by express courier." },
        { jp: "なるべく色物は白い物と分けてお洗いなさい。", en: "Try to keep the colours separate from the whites." },
        { jp: "誰かもう給仕を受けましたか。", en: "Has anyone served you, yet?" },
        { jp: "次の打ち合わせは13日の金曜日の午後1時に設定された。", en: "The next meeting is set for 1 p.m. on Friday the 13th." },
        { jp: "私達は昼食にピザとワイン２本を二人で分けました。", en: "We shared a pizza and 2 bottles of wine, for lunch." },
        { jp: "そのスープはすごい香り。何が入っているの？", en: "The soup smells so good! What's in it?" },
        { jp: "湯気の立つ熱いお風呂につかるのが大好きです。", en: "I love to soak in a steaming hot bath." },
        { jp: "この店は日本の骨董品を専門にしています。", en: "This shop specializes in Japanese antiques." },
        { jp: "もうこれ以上あなたに時間やお金をかけたくない。", en: "I don't want to spend any more time or money on you." },
        { jp: "その問題への解決策を提案したい。", en: "I'd like to suggest a solution to the problem." },
        { jp: "何時なら都合がいいですか。", en: "What time suits you?" },
        { jp: "自衛隊は避難者に食料と水を供給した。", en: "The Self Defense Force supplied food & water to the evacuees." },
        { jp: "この薬は食事の前に飲むべきか、それとも後ですか。", en: "Should I take this medicine before or after meals?" },
        { jp: "私達はテスト結果の話をしていただけです。", en: "We were just talking about the test results." },
        { jp: "このケーキはあなたにとって悪い味ですか。", en: "Does this cake taste bad to you?" },
        { jp: "私が父に写真のインスタグラムへの投稿方法を教えた。", en: "I taught my dad how to post photos on Instagram." },
        { jp: "なぜあなたがそう思うのか、その理由を教えてください。", en: "Will you tell me the reason why you think so?" },
        { jp: "応急処置の訓練を受けています。", en: "I've been trained in first aid." },
        { jp: "以前、ヨーロッパを旅行したことがありますか。", en: "Have you ever travelled around Europe before?" },
        { jp: "ケヴィン、あなたが伝えようとしている点は何ですか。", en: "Kevin, what is the point you're trying to make?" },
        { jp: "蛇口をしっかり閉めてくれますか。", en: "Can you please turn the taps off, tight?" },
        { jp: "私達のサービスをご利用いただきありがとうございます。", en: "Thank you for using our service." },
        { jp: "大阪にいた時、バークレーの新宅に会いに行きましたか。", en: "Did you visit Barclay, while you were in Osaka?" },
        { jp: "次の電車まで、どのくらい待たないといけないの？", en: "How long do we have to wait for the next train?" },
        { jp: "水を無駄にしないで。それが私達に残された全てです。", en: "Please don't waste the water, it's all we have left." },
        { jp: "大きな子供達（大人達）はテレビでフットボールを見ています。", en: "The \"big\" kids (adults) are watching the footy on TV." },
        { jp: "日本が男子100mリレーで金メダルを取りました。", en: "Japan won gold in the men's 100m relay race." },
        { jp: "私達は皆に良い新年を願いました。", en: "We wished everyone a Happy New Year!" }
    ]
};
